### ISSUE TITLE
OptionsScreenSpinnerRow only allows data types of numbers and strings

### ISSUE THREAD

**Issue by MaksymKurny** [zgibberish/rotwood-modmenu#1]
![image](https://github.com/user-attachments/assets/3a8c0173-7fe3-449b-83d2-642377928064)

configuration_options = {
	{
        name = "auto_update",
		label = "Auto update",
		hover = "Automatically update the translation file as soon as a new version is available",
        options =
        {
            {description = "Yes", data = true},
            {description = "No", data = false},
        },
        default = true,
    },
}

[00:05:24.095]: [string "...s/modmenu/widgets/optionsscreenspinnerrow.lua"]:127: Use OptionsScreenToggleRow for bools.
LUA ERROR stack traceback:
=[C]:-1 in (global) assert (C) <-1--1>
../mods/modmenu/scripts/modmenu/widgets/optionsscreenspinnerrow.lua:127 in (method) SetValues (Lua) <126-139>
   self =
      altcontrolup_sound = UI/_defaults/input_up
      dirtytransform = false
      animate_scale_out_timing = 0.2

**Comment by zgibberish** [comment]
Hi @MaksymKurny! Thanks for creating the issue, I just tested with an empty mod using the same `configuration_options` as yours, I can confirm it's an issue with Mod Menu, specifically the mod configuration screen.

I used `OptionsScreenSpinnerRow` to display and select mod config options, which only allows strings and numbers for options' data types, see below:

```lua
function OptionsScreenSpinnerRow:SetValues(values)
	assert(type(values[1].data) ~= "boolean", "Use OptionsScreenToggleRow for bools.")
	-- I don't think there's a hard requirement on type, but you probably want
	-- an enum string since settings has support for them.
	assert(type(values[1].data) == "string" or type(values[1].data) == "number", "Are you storing the right kind of data?")

	OptionsScreenSpinnerRow._base.SetValues(self, values)
	if #self.values > 0 then
		-- TODO(ui): Does changing this to be after _SetValue break things?
		self.pagination:SetCount(#self.values)
	end

	return self
end
```

Fixing this would probably need some edits to `OptionsScreenSpinnerRow` or maybe a bit more, I can't promise anything atm cuz I'm focusing on some other projects , you can work around this by using strings or numbers for `data` instead, like this:

```lua
configuration_options = {
    {
        name = "auto_update",
        label = "Auto update",
        hover = "Automatically update the translation file as soon as a new version is available",
        options =
        {
            {description = "Yes", data = 1},
            {description = "No", data = 0},
        },
        default = 1,
    },
}
```

And check them as numbers and not booleans, e.g:

```lua
local auto_update_is_on = GetModConfigData("auto_update", true) == 1 and true or false
```

(Or just `GetModConfigData(name)` if you're using the new modloader!)

I hope this helps, please share if you're still stuck on anything, I'd gladly answer your questions.

**Comment by zgibberish** [comment]
@MaksymKurny I just pushed a fix that should resolve this, you can try the latest beta [2.0.0-beta1c](https://github.com/zgibberish/rotwood-modmenu/releases/tag/2.0.0-beta1c) (modwrangler branch)

commit: 64dca3ebd78f7a742897f8d82757420e7c7125d0

If all is well then I will close this issue soon, thanks again for reporting it! If there's still issues please let me know tho 🪵
